### ISSUE TITLE
Too many new features ;-)

### ISSUE THREAD

**Issue by DecaTec** [nextcloud/windows-universal#134]
When the new version of the app is installed, it shows the "what's new" dialog. We already have so many new features, that this dialog doesn't fit on the screen (Lumia 950).

We should make this dialog scrollable.

**Comment by DecaTec** [comment]
I've tried to make the ContentDialog scrollable (for the content), but the content itself is not the problem here. Looks like a misbehavior of the dialog itself. On the phone, there would be enough place for the buttons, but the size of the whole dialog exceeds the bounds of the display.

**Comment by DecaTec** [comment]
Unfortunately, this still doesn't work (tested on Lumia 950). No scroll bar and the buttons dsiappear on the buttom of the screen.

**Comment by SunboX** [comment]
Hm, it worked on mine (950). I will have a look again.

**Comment by SunboX** [comment]
Works for me, latest master:




<img src="https://user-images.githubusercontent.com/83344/27655817-f6c9306a-5c46-11e7-8110-b7c131870c6f.png" width="320">
<img src="https://user-images.githubusercontent.com/83344/27655818-f6cbfd7c-5c46-11e7-802d-c2cbc513836f.png" width="320">
<img src="https://user-images.githubusercontent.com/83344/27655819-f6d9aad0-5c46-11e7-988f-110952c81455.png" width="320">

**Comment by DecaTec** [comment]
Ok, will verify the next days

**Comment by DecaTec** [comment]
Tested it and no: the buttons are not really visible. First screenshot shows the screen when scrolled down to the buttom:

![wp_ss_20170701_0001 1](https://user-images.githubusercontent.com/9428899/27761993-6307f9dc-5e68-11e7-90ea-3dc163969213.png)
![wp_ss_20170701_0002 1](https://user-images.githubusercontent.com/9428899/27761994-68372afe-5e68-11e7-8bea-aaa25319f15d.png)

**Comment by SunboX** [comment]
Hm, it really works on mine. Looks like a Windows issue... seems like it does not recognize the onscreen hardware-buttons bar.
Let me try something, but I can not test it. 😏

**Comment by DecaTec** [comment]
Just let me know, then I can give it another try.

**Comment by SunboX** [comment]
It's a bit ugly, but it should solve the issue: https://github.com/nextcloud/windows-universal/pull/216

**Comment by DecaTec** [comment]
Sorry, but still the same problem.
Could you try to pull the buttons into the ScrollViewer so that they will appear by scrolling down?

**Comment by DecaTec** [comment]
Merged https://github.com/nextcloud/windows-universal/pull/216
Should be OK for now.
